### ISSUE TITLE
THE FUCKING BITERS CAN RUN AS FAST AS THEY WANT ON WATER

### ISSUE THREAD

**Issue by DeaSTL** [NoxyNixie/Noxys_Swimming#1]
Pls fix, thank you

**Comment by NoxyNixie** [comment]
I see no problem with them going as fast as they can ;)

But honestly the problem isn't an easy fix and may in fact cause significant game slowdowns when a group of biters decide to walk on water.

So unfortunately for you I have no intention to fix this. If you can come up with a pull request that won't affect deathworld multiplayer servers then I'll likely accept it but I'm not sure this is an easy task or possible.
