### ISSUE TITLE
Wrong birth position

### ISSUE THREAD

**Issue by jackychen2005** [NoxyNixie/Noxys_Swimming#2]
Often born on an island other than the one with the original box;
There is no problem if the Noxy'swimming module is installed.
I hope the author can fix it

**Comment by NoxyNixie** [comment]
I'm not sure this is an issue with my Swimming mod since I don't touch spawning mechanics at all.

**Comment by jackychen2005** [comment]
Sorry, sorry, my feedback is wrong.
